---

- name: "Set profile file name to {{ macos_profile__identifierPrefix }}.{{ mobileconfig.template }}"
  set_fact:
    macos_profile__profile: "{{ macos_profile__identifierPrefix }}.{{ mobileconfig.template }}"

# grep returns an exit code of 1 when it doesn't match any lines
- name: "Check if profile {{ macos_profile__profile }} is installed at computer level"
  shell: /usr/bin/profiles -C | grep -w "{{ macos_profile__profile }}"
  ignore_errors: yes
  changed_when: False
  register: installedprofile

- include: profile_present.yml
  when: mobileconfig.state == "present"

- include: profile_absent.yml
  when: mobileconfig.state == "absent"
